package com.ahmedpasha.smartfarm.balegh
enum class BaleghIntent { GENERAL_QUERY, FARM_STATUS, CREATE_TASK, INVENTORY_QUERY, PURCHASE_ACTION, SALE_ACTION, WORKER_QUERY, CROP_QUERY, LAND_QUERY, FINANCE_QUERY, PROBLEM_REPORT, COMMITMENT, UNKNOWN }
